### ISSUE TITLE
Mix tasks to generate a Model/Resource

### ISSUE THREAD

**Issue by flaviogranero** [inaka/Dayron#49]
* A simple generator as Ecto provides
* Research if importing models from an api schema.json file is possible

**Comment by tiagoengel** [comment]
@flaviogranero I just realized that I forgot to add a tag to close this issue in the PR. I think this issue can be closed. Do you want to keep it open to add support for json schemas?

**Comment by flaviogranero** [comment]
@tiagoengel yes, let's close it and if we decide to work on schema.json, we open another issue.
